---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: citusclusters.jw3.xyz
spec:
  scope: Namespaced
  names:
    kind: CitusCluster
    plural: citusclusters
    singular: cituscluster
    shortNames:
      - cc
  group: jw3.xyz
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
              pattern: ^jw3.xyz/v1alpha1$
            kind:
              type: string
              pattern: ^CitusCluster$
            spec:
              type: object
              properties:
                name:
                  type: string
                workers:
                  type: integer
                worker_storage:
                  type: integer
